//AUTHENTICATION ACTIONS
export const SIGN_IN = "SIGN IN"
export const LOG_OUT = "LOG OUT"
export const SIGN_UP = "SIGN UP"

//ERROR MANAGER
export const INVALID_EMAIL = "INVALID_EMAIL"
export const INVALID_PASSWORD = "INVALID_PASSWORD"
export const MISSING_PASSWORD = "MISSING_PASSWORD"
export const MISSING_EMAIL = "MISSING_EMAIL"
export const PASSWORDS_NOT_MATCH = "PASSWORDS_NOT_MATCH"
export const WRONG_CREDENTIALS = "WRONG_CREDENTIALS"


//CART MANAGER
export const FETCH_FOOD = "FETCH_FOOD";

//RECIPES MANAGER

export const FETCH_RECIPES = "FETCH_RECIPES";